/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NodeAttributesFrame.java
 *
 * Created on May 9, 2010, 5:49:26 PM
 */

/**
 *
 * @author michael
 */
public class NodeAttributesFrame extends javax.swing.JFrame {

    /** Creates new form NodeAttributesFrame */
    public NodeAttributesFrame(y.view.Graph2DView view, layout.GraphRealizer graphRealizer)
    {
        this.view = view;
        this.graphRealizer = graphRealizer;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pointAttributesPanel = new javax.swing.JPanel();
        pointWidthSlider = new javax.swing.JSlider();
        pointHeightSlider = new javax.swing.JSlider();
        pointWidthLabel = new javax.swing.JLabel();
        pointHeightLabel = new javax.swing.JLabel();
        pointShapeLabel = new javax.swing.JLabel();
        pointShapeComboBox = new javax.swing.JComboBox();
        currentPointWidthLabel = new javax.swing.JLabel();
        currentPointHeightLabel = new javax.swing.JLabel();
        borderLineType = new javax.swing.JLabel();
        borderLineTypeComboBox = new javax.swing.JComboBox();
        showLabelsCheckBox = new javax.swing.JCheckBox();
        selectPointBorderColorPanel = new javax.swing.JPanel();
        previewPointBorderColorPanel = new javax.swing.JPanel();
        choosePointBorderColorButton = new javax.swing.JButton();
        selectPointFillColorPanel = new javax.swing.JPanel();
        previewPointFillColorPanel = new javax.swing.JPanel();
        choosePointFillColorButton = new javax.swing.JButton();
        transparent = new javax.swing.JCheckBox();
        applyButton = new javax.swing.JButton();

        setTitle("Node Attributes");
        setMinimumSize(new java.awt.Dimension(350, 500));
        setPreferredSize(new java.awt.Dimension(350, 500));

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        pointAttributesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Node Attributes"));
        pointAttributesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pointWidthSlider.setMaximum(150);
        pointWidthSlider.setMinimum(2);
        pointWidthSlider.setValue(15);
        pointWidthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pointWidthSliderStateChanged(evt);
            }
        });
        pointAttributesPanel.add(pointWidthSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        pointHeightSlider.setMaximum(150);
        pointHeightSlider.setMinimum(2);
        pointHeightSlider.setValue(15);
        pointHeightSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pointHeightSliderStateChanged(evt);
            }
        });
        pointAttributesPanel.add(pointHeightSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 120, 30));

        pointWidthLabel.setText("Width:");
        pointAttributesPanel.add(pointWidthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 20));

        pointHeightLabel.setText("Height:");
        pointAttributesPanel.add(pointHeightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        pointShapeLabel.setText("Shape:");
        pointAttributesPanel.add(pointShapeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 20));

        pointShapeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ellipse", "Rectangle" }));
        pointAttributesPanel.add(pointShapeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, -1));

        currentPointWidthLabel.setText("10");
        pointAttributesPanel.add(currentPointWidthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 20, -1));

        currentPointHeightLabel.setText("10");
        pointAttributesPanel.add(currentPointHeightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 20, -1));

        borderLineType.setText("Border Line:");
        pointAttributesPanel.add(borderLineType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, 20));

        borderLineTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Dashed" }));
        pointAttributesPanel.add(borderLineTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 120, -1));

        showLabelsCheckBox.setText("Show Labels");
        pointAttributesPanel.add(showLabelsCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, -1));

        selectPointBorderColorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Border"));
        selectPointBorderColorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previewPointBorderColorPanel.setBackground(new java.awt.Color(204, 204, 0));
        selectPointBorderColorPanel.add(previewPointBorderColorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 20));

        choosePointBorderColorButton.setText("Select Color");
        choosePointBorderColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePointBorderColorButtonActionPerformed(evt);
            }
        });
        selectPointBorderColorPanel.add(choosePointBorderColorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 20));

        selectPointFillColorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Fill Color"));
        selectPointFillColorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        previewPointFillColorPanel.setBackground(new java.awt.Color(204, 204, 0));
        selectPointFillColorPanel.add(previewPointFillColorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 50, 20));

        choosePointFillColorButton.setText("Select Color");
        choosePointFillColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePointFillColorButtonActionPerformed(evt);
            }
        });
        selectPointFillColorPanel.add(choosePointFillColorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 130, 20));

        transparent.setText("Transparent");
        transparent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                transparentItemStateChanged(evt);
            }
        });
        selectPointFillColorPanel.add(transparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addComponent(selectPointFillColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(applyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(selectPointBorderColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(pointAttributesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointAttributesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectPointBorderColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectPointFillColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(applyButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pointWidthSlider.setValue(this.graphRealizer.getNodeWidth());
        pointHeightSlider.setValue(this.graphRealizer.getNodeHeight());
        previewPointFillColorPanel.setBackground(this.graphRealizer.getFillColor());
        previewPointBorderColorPanel.setBackground(this.graphRealizer.getLineColor());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pointWidthSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pointWidthSliderStateChanged
        currentPointWidthLabel.setText(""+pointWidthSlider.getValue());
}//GEN-LAST:event_pointWidthSliderStateChanged

    private void pointHeightSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pointHeightSliderStateChanged
        currentPointHeightLabel.setText(""+pointHeightSlider.getValue());
}//GEN-LAST:event_pointHeightSliderStateChanged

    private void choosePointBorderColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePointBorderColorButtonActionPerformed
        java.awt.Color color = javax.swing.JColorChooser.showDialog(null, "Choose Color", previewPointBorderColorPanel.getBackground());
        if (color != null) {
            previewPointBorderColorPanel.setBackground(color);
            repaint();
        }
}//GEN-LAST:event_choosePointBorderColorButtonActionPerformed

    private void choosePointFillColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePointFillColorButtonActionPerformed
        java.awt.Color color = javax.swing.JColorChooser.showDialog(null, "Choose Color", previewPointFillColorPanel.getBackground());
        if (color != null) {
            previewPointFillColorPanel.setBackground(color);
            repaint();
        }
}//GEN-LAST:event_choosePointFillColorButtonActionPerformed

    private void transparentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_transparentItemStateChanged
        if(evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            previewPointFillColorPanel.setEnabled(false);
            choosePointFillColorButton.setEnabled(false);
        } else {
            previewPointFillColorPanel.setEnabled(true);
            choosePointFillColorButton.setEnabled(true);
        }
}//GEN-LAST:event_transparentItemStateChanged

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        this.graphRealizer.setNodeWidth(new Integer(pointWidthSlider.getValue()).intValue());
        this.graphRealizer.setNodeHeight(new Integer(pointHeightSlider.getValue()).intValue());

        this.graphRealizer.setFillColor(previewPointFillColorPanel.getBackground());
        this.graphRealizer.setFillColor2(previewPointFillColorPanel.getBackground());

        this.graphRealizer.setLineColor(previewPointBorderColorPanel.getBackground());

        if (pointShapeComboBox.getSelectedItem().equals("Rectangle")) {
            this.graphRealizer.setNodeShape(y.view.ShapeNodeRealizer.RECT);
        } else {
            this.graphRealizer.setNodeShape(y.view.ShapeNodeRealizer.ELLIPSE);
        }
        this.graphRealizer.updateGraph();

        if (this.showLabelsCheckBox.isSelected())
        {
            for (y.base.NodeCursor nc = this.view.getGraph2D().nodes(); nc.ok(); nc.next())
            {
                this.view.getGraph2D().getRealizer(nc.node()).setLabelText(""+nc.node().index());
            }
         }
        else
        {
            for (y.base.NodeCursor nc = this.view.getGraph2D().nodes(); nc.ok(); nc.next())
            {
               this.view.getGraph2D().getRealizer(nc.node()).setLabelText("");
            }
        }
       
        view.updateView();
        super.setVisible(false);
}//GEN-LAST:event_applyButtonActionPerformed

    //Extra variables
    private y.view.Graph2DView view;
    private layout.GraphRealizer graphRealizer;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel borderLineType;
    private javax.swing.JComboBox borderLineTypeComboBox;
    private javax.swing.JButton choosePointBorderColorButton;
    private javax.swing.JButton choosePointFillColorButton;
    private javax.swing.JLabel currentPointHeightLabel;
    private javax.swing.JLabel currentPointWidthLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pointAttributesPanel;
    private javax.swing.JLabel pointHeightLabel;
    private javax.swing.JSlider pointHeightSlider;
    private javax.swing.JComboBox pointShapeComboBox;
    private javax.swing.JLabel pointShapeLabel;
    private javax.swing.JLabel pointWidthLabel;
    private javax.swing.JSlider pointWidthSlider;
    private javax.swing.JPanel previewPointBorderColorPanel;
    private javax.swing.JPanel previewPointFillColorPanel;
    private javax.swing.JPanel selectPointBorderColorPanel;
    private javax.swing.JPanel selectPointFillColorPanel;
    private javax.swing.JCheckBox showLabelsCheckBox;
    private javax.swing.JCheckBox transparent;
    // End of variables declaration//GEN-END:variables

}
